/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.jetbrains.kotlin.jvm") version "1.7.0"
    application
    `maven-publish`
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://jitpack.io")
        content {
            includeGroup("com.github.Alexiscomete")
        }
    }
}

dependencies {
    implementation("org.javacord:javacord:3.6.0")
    implementation("org.xerial:sqlite-jdbc:3.36.0.3")
    implementation("org.json:json:20220320")
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.7.0")
    implementation("com.github.Alexiscomete:procedural_generation:Tagtest6")
}

application {
    mainClass.set("io.github.alexiscomete.lapinousecond.MainKt")
}

group = "io.github.alexiscomete.lapinoudsecond"
version = "1.0-SNAPSHOT"
description = "A-Discord-Adventure"
java.sourceCompatibility = JavaVersion.VERSION_11

tasks.jar {
    manifest {
        attributes["Main-Class"] = "io.github.alexiscomete.lapinousecond.MainKt"
    }
    configurations["compileClasspath"].forEach { file: File ->
        println(file.name)
        from(zipTree(file.absoluteFile))
    }
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/Alexiscomete/A-Discord-Adventure")
            credentials {
                username = project.findProperty("gpr.user") as String? ?: System.getenv("USERNAME")
                password = project.findProperty("gpr.key") as String? ?: System.getenv("TOKEN")
            }
        }
    }
    publications {
        register<MavenPublication>("gpr") {
            artifactId = "ada"
            artifact(tasks.distZip)
        }
    }
}
