/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "A-Discord-Adventure"
include(":ManageSave", ":A-Discord-Adventure")
project(":ManageSave").projectDir = File("../ADA modules/ManageSave")
